# -*- coding: utf-8 -*-
"""Plotting in PowerBI with python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sbj0vMKWTArYx8sQsreQEv7g9EnHkI3O
"""

import matplotlib.pyplot as plt

# Crea un histograma
# Define los límites del eje x para el histograma
x_min = -10 # Límite inferior del rango
x_max = 30   # Límite superior del rango

# Conversión de píxeles a pulgadas


plt.rcParams.update({'font.size': 12})
plt.subplots_adjust(left=0.05, right=0.95, top=0.99, bottom=0.2)
delivery_delay_days = dataset['delivery_delay_hours']/24

plt.hist(delivery_delay_days, bins=40, color='#00DB92',range=(x_min, x_max),edgecolor='#91E9DB')
plt.xlabel('Dias')